services:
  - type: web
    name: anomaly-detection-api
    env: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app'
    plan: free
